# config.yaml
model:
  width: 256
  depth: 5
  dim_in: 2
  dim_out: 1
  latent_dim: 64
  layer_sizes: [256, 512]
  w0: 1.0
  modulate_scale: true
  modulate_shift: true
  device: "cuda"  # Use "cuda" for GPU or "cpu" for CPU

training:
  latent_init_scale: 0.01
  outer_lr: 0.0001
  inner_lr: 0.001
  l2_weight: 0.000001
  inner_steps: 10
  resolution: 256
  batch_size: 32
  n_epochs: 10

paths:
  data_dir: "/home/tempus/projects/functa_torch/triangles"
  checkpoints_dir: "/home/tempus/projects/functa_torch/checkpoints"