# config.yaml
model:
  width: 256
  depth: 10
  dim_in: 2
  dim_out: 1
  latent_dim: 64
  layer_sizes: null
  w0: 30.0
  modulate_scale: false
  modulate_shift: true
  device: "cuda"  # Use "cuda" for GPU or "cpu" for CPU

training:
  latent_init_scale: 0.01
  outer_lr: 3e-6
  inner_lr: 0.01
  l2_weight: 0
  inner_steps: 3
  resolution: 256
  batch_size: 5
  n_epochs: 500
  save_ckpt_step: 100

paths:
  data_dir: "/home/tempus/projects/functa_torch/triangles"
  checkpoints_dir: "/home/tempus/projects/functa_torch/checkpoints_testing"